-- MySQL Script generated by MySQL Workbench
-- Thu Dec  8 13:04:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jaysdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jaysdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jaysdb` DEFAULT CHARACTER SET utf8 ;
USE `jaysdb` ;

-- -----------------------------------------------------
-- Table `jaysdb`.`menuItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jaysdb`.`menuItem` (
  `itemID` INT(11) NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `calories` INT(11) NULL DEFAULT NULL,
  `isAvailable` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`itemID`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jaysdb`.`siteUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jaysdb`.`siteUser` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `passwordHash` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `accountType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jaysdb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jaysdb`.`order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `placedTime` DATETIME(10) NOT NULL,
  `forTime` DATETIME(10) NOT NULL,
  `siteUser_userID` INT NOT NULL,
  PRIMARY KEY (`orderID`, `siteUser_userID`),
  UNIQUE INDEX `orderID_UNIQUE` (`orderID` ASC) VISIBLE,
  INDEX `fk_order_siteUser1_idx` (`siteUser_userID` ASC) VISIBLE,
  CONSTRAINT `fk_order_siteUser1`
    FOREIGN KEY (`siteUser_userID`)
    REFERENCES `jaysdb`.`siteUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jaysdb`.`orderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jaysdb`.`orderItem` (
  `menuItem_itemID` INT(11) NOT NULL,
  `order_orderID` INT NOT NULL,
  `quantity` INT NOT NULL,
  `notes` VARCHAR(180) NULL,
  PRIMARY KEY (`menuItem_itemID`, `order_orderID`),
  INDEX `fk_orderItem_order1_idx` (`order_orderID` ASC) VISIBLE,
  CONSTRAINT `fk_orderItem_menuItem`
    FOREIGN KEY (`menuItem_itemID`)
    REFERENCES `jaysdb`.`menuItem` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderItem_order1`
    FOREIGN KEY (`order_orderID`)
    REFERENCES `jaysdb`.`order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jaysdb`.`favoriteItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jaysdb`.`favoriteItem` (
  `siteUser_userID` INT NOT NULL,
  `menuItem_itemID` INT(11) NOT NULL,
  PRIMARY KEY (`siteUser_userID`, `menuItem_itemID`),
  INDEX `fk_favoriteItem_menuItem1_idx` (`menuItem_itemID` ASC) VISIBLE,
  CONSTRAINT `fk_favoriteItem_siteUser1`
    FOREIGN KEY (`siteUser_userID`)
    REFERENCES `jaysdb`.`siteUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoriteItem_menuItem1`
    FOREIGN KEY (`menuItem_itemID`)
    REFERENCES `jaysdb`.`menuItem` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
