INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('French Fries','Sides',2.75,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Cheese Fries','Sides',3.75,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Curly Fries','Sides',2.75,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Onion Rings','Sides',4.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Mozzarella Sticks','Sides',4.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Pierogies','Sides',3.75,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Potato Skins','Sides',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Tuna Melt','Hot Sandwiches',4.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Grilled Cheese','Hot Sandwiches',3.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Grilled Ham & Cheese','Hot Sandwiches',4.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('BLT','Hot Sandwiches',3.75,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Turkey Pretzel Melt','Hot Sandwiches',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Hamburger Sub','Hot Sandwiches',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Cheeseburger Sub','Hot Sandwiches',4.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Hamburger','Burgers',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Cheeseburger','Burgers',5.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Bacon Cheddar Burger','Burgers',6,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Beyond Burger','Burgers',6,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Beef & Cheese','Steak Sandwiches',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Chicken Cheese','Steak Sandwiches',5.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Chicken Ranch','Steak Sandwiches',5.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Buffalo Beef','Steak Sandwiches',5.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Buffalo Chicken','Steak Sandwiches',5.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Crispy Chicken','Chicken Sandwiches',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Buffalo Chicken','Chicken Sandwiches',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Chicken Parmesan','Chicken Sandwiches',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Grilled Chicken','Chicken Sandwiches',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Chicken Strips','Chicken Sandwiches',5.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Buffalo Chicken Strips','Chicken Sandwiches',5.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Egg Jay','Breakfast',3,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Egg Jay on Bagel','Breakfast',4.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Hash Brown','Breakfast',1.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Jays Omelet','Breakfast',4.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Banana Pita Pocket','Healthy Options',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Chicken Caesar Pita Pocket','Healthy Options',5.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Tuna Bowl','Healthy Options',6.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Chicken Bowl','Healthy Options',6.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Chicken Bacon Ranch Bowl','Healthy Options',6.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Cheese Pizza','Pizza',4.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Pepperoni Pizza','Pizza',5.75,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Cheese Flat Bread','Pizza',5.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('South Western Flatbread','Pizza',5.75,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Buffalo Chicken Ranch Flatbread','Pizza',5.75,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('BBQ Chicken Flatbread','Pizza',5.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Italian Chicken Wrap','Quesadillas',5.25,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Cheese Quesadilla','Quesadillas',4.5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Chicken Quesadilla','Quesadillas',6,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Crispy Chicken Quesadilla','Quesadillas',6,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Buffalo Chicken Quesadilla','Quesadillas',5,NULL,NULL,1,NULL);
INSERT INTO menuItem(itemName,category,price,description,calories,isAvailable,imgSource) VALUES ('Chicken Fajita Quesadilla','Quesadillas',6.25,NULL,NULL,1,NULL);
